# 博客配置
keywords: VLSI
author: Minghaooo
description: 打死不转CS。<br> VLSI 大法好！
avatar: /images/favicon.ico
beian: 苏B备AE86号
copyright: 1995 - 2020 




# 社交账号
github: https://github.com/Minghaooo
mail: mailto:tmhwisc@gmail.com
zhihu: https://www.zhihu.com/people/tangmh1101
#QQ: http://sighttp.qq.com/authd?IDKEY=1248439953

  

# Valine 评论，如何配置请看官网 https://valine.js.org
valine:
  enable: true # if you want use valine, please set enable: true
  appid: 
  appkey: 
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: mp # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: 打死不转CS # comment box placeholder
  serverURLs: 

menu:
  home: /
  #commonweal: /404.html
# 百度统计设置
# 请访问 https://tongji.baidu.com/ 
# 获取统计JS代码放入 anatole-core/source/js/baidu-tongji.js
# 不想设置请进入 anatole-core/layout/partial/layout.pug 文件
# 删除 script(src=url_for("/js/baidu-tongji.js")) 此行

# 留言板页面和关于页面，请在source文件夹下新建guestbook、about文件夹，然后再文件夹新建index.md文件；如不需要评论请在两个---中增加comments: false。

# 如有报错，请查看主题下package.json文件的插件是否已经安装，安装版本一般无所谓，已安装的插件可以在hexo目录下的package.json查看。
# 安装命令如下 npm install 插件名 --save

# 左下角的猫：https://github.com/EYHN/hexo-helper-live2d
# Live2D
## https://github.com/EYHN/hexo-helper-live2d

